In [2]:
#1version printing
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Sagar\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [10]:
#2 printing array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
arr=np.arange(10)
arr

[1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#3 printing array 
import numpy as np
np.ones((3,3),dtype=np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#4 odd number
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[arr1%2==0]
arr1[arr1%2!=0]

array([1, 3, 5, 7, 9])

In [23]:
#5 -1 in several positin
import numpy as np
arr2=np.array([1,2,3,4,5,6,7,8,9])
arr2[arr2%2!=0]=-1
print(arr2)
arr3=np.array([1,2,3,4,5,6,7,8,9])
arr3[arr3%2==0]=-1
arr3

[-1  2 -1  4 -1  6 -1  8 -1]


array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])

In [ ]:
#6

In [29]:
#7
import numpy as np
arr=np.arange(50).reshape(5,10)
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
#8 reshape and arange
import numpy as np
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
#9
import numpy as np
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
np.hstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [3]:
#10 and 11 intersect and generate custom sequence
import numpy as np
a=[1,2,3]
b=np.repeat(a,3)
c=np.tile(a,3)
r=np.concatenate((b,c))
e=np.intersect1d(b,c)
print(e)
print(r)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [6]:
#12 remove items which in another array
import numpy as np
a=[1,2,3]
b=np.array([1,2,3,4,5,6,7,8,9])
c=np.tile(a,3)
r=np.setdiff1d(b,c)
print(r)

[4 5 6 7 8 9]


In [7]:
#13 getting positions where array match
import numpy

a = numpy.array([0, 1, 2, 3, 4, 5, 6])
b = numpy.array([6, 5, 4, 3, 2, 1, 6])
r=numpy.where(a==b)
print(r)

(array([3, 6], dtype=int64),)


In [17]:
#14 extracting all number in a range
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.where((a>5) & (a<8))
c=a[(a>5)&(a<9)]
print(c)
print(b)


[6 7 8]
(array([5, 6], dtype=int64),)


In [18]:
int(True)

1

In [2]:
#15
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)


array([6., 7., 9., 8., 9., 7., 5.])

In [3]:
pip install scipy


Note: you may need to restart the kernel to use updated packages.


In [1]:
help(np.array)

NameError: name 'np' is not defined

In [2]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [3]:
pip3 install jupyter-tabnine
jupyter nbextension install --py jupyter_tabnine
jupyter nbextension enable --py jupyter_tabnine
jupyter serverextension enable --py jupyter_tabnine


SyntaxError: invalid syntax (<ipython-input-3-4f643ec26704>, line 1)

In [4]:
hinterland.hint_delay

NameError: name 'hinterland' is not defined

In [5]:
%config IPCompleter.greedy=True

In [6]:
conda install -c conda-forge jupyter_nbextensions_configurator

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Sagar\anaconda3

  added / updated specs:
    - jupyter_nbextensions_configurator


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |   py37hc8dfbb8_1         3.1 MB  conda-forge
    jupyter_contrib_core-0.3.3 |             py_2          15 KB  conda-forge
    jupyter_nbextensions_configurator-0.4.1|           py37_0         487 KB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

  jupyter_contrib_c~ conda-forge/noarch::jupyter_contrib_core-0.3.3-py_2
  jupyter_nbextensi~ conda-forge/win-64::jupyter_nbextensions_configurator-0.4.1-py37_0
  python_abi   



==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda





Note: you may need to restart the kernel to use updated packages.


In [7]:
jupyter nbextension enable hinterland/hinterland

SyntaxError: invalid syntax (<ipython-input-7-220a3d076571>, line 1)

In [8]:
jupyter contrib nbextension install --user

SyntaxError: invalid syntax (<ipython-input-8-1c0e089b301b>, line 1)

In [10]:
 enable hinterland/hinterland

SyntaxError: invalid syntax (<ipython-input-10-515d1fc579a3>, line 1)

In [1]:
jupyter nbextension enable hinterland/hinterland

SyntaxError: invalid syntax (<ipython-input-1-220a3d076571>, line 1)

In [ ]:
import numpy as np
np.array(int())