In [4]:
a=5
a.bit_length()

3

In [13]:
class computer:
    def __init__(self,ram,pc):
        self.ram1=ram
        self.pc1=pc
    def config(self):
        print("config is",self.ram1,self.pc1)
comp1=computer("16gb","asus")
comp2=computer("32gb","php")
comp1.config()
comp2.config()
        
        

config is 16gb asus
config is 32gb php


In [28]:
class rectangle:
    def __init__(self,height,weight):
        self.height=height
        self.weight=weight
    def area(self):
        return (self.height*self.weight)
a=rectangle(5,6)

print(a.area())
    

30


In [24]:
class string:
    def __init__(self,a):
        self.a=a
    def get_string(self):
        return self.a
  
    def print_string(self):
        print(self.a.upper())
s=string(input())    
s.get_string()
s.print_string()
        
    

sagar
SAGAR


In [39]:
class student:
    def __init__(self,roll,ids):
        self.roll=roll
        self.ids=ids
        self.lap=self.laptop()
    def show(self):
        print(self.roll,self.ids)
        self.lap.show()
    class laptop:
        def __init__(self):
            self.color="ash"
            self.disk="4gb"
            self.hard="nividia"
        def show(self):
            print(self.color,self.disk,self.hard)
           
        
s1=student(2,5)
s2=student(3,4)
s1.show()
s2.show()
#lap=student.laptop()
#lap.show()
        
    
        
    

2 5
ash 4gb nividia
3 4
ash 4gb nividia


In [55]:
class A:
    def __init__(self):
        print("sagar is good boy")
    def func1(self):
        print("sagar1 is good boy")
    def func2(self):
        print("sagar2 is good boy")  
class B():
    def __init__(self):
        print("sagar fgdfgf is good boy")
    
    def func3(self):
        print("sagar3 is good boy")
    def func4(self):
        print("sagar4 is good boy")
class C(A,B):
    
    def __init__(self):
        super().__init__()
        super().__init__()
        print("hbfbvhdfhvbhjf")
    def func3(self):
        print("sagar5 is good boy")
    def func4(self):
        print("sagar6 is good boy")
    
        
a1=A()
a1.func1()
b1=B()
b1.func3()
c1=C()


    
        
        

sagar is good boy
sagar1 is good boy
sagar fgdfgf is good boy
sagar3 is good boy
sagar is good boy
sagar is good boy
hbfbvhdfhvbhjf


In [59]:
class pycharm:
    def execute(self):
        print("running")
        print("compiling")
        
        
class pycharm1:
    def execute(self):
        print("running")
        print("compiling")
        print("spellchecking")
        print("xcdghfj")

class laptop:
    def code(self,ide):
        ide.execute()
        
        
        
ide=pycharm1()
lap1=laptop()
lap1.code(ide)
    

running
compiling
spellchecking
xcdghfj


In [91]:
class student:
    def __init__(self,m1,m2):
        
        self.m1=m1
        self.m2=m2
        
        
    def __add__(self,othr):
        m1=self.m1+othr.m1
        m2=self.m2+othr.m2
        s3=student(m1,m2)
    
    def __get__(self,other):
        r1=self.m1+other.m2
        r2=self.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
    def __str__(self):
        return '{} {} '.format(self.m1,self.m2)
    
        
        

        
s1=student(10,20)
s2=student(30,50)
s3=s1+s2
if s1 > s2:
    print("s1 win")
else:
    print("s2 win")



TypeError: '>' not supported between instances of 'student' and 'student'

In [6]:
import numpy as np
x=[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
x
y=np.array(x)
y




array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
np.arange(1,101).reshape(10,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
x=np.linspace(10,200,10)
x

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [23]:
x.max()

200.0

In [24]:
x.min()

10.0

In [26]:
np.random.randn(2,3)

array([[-0.11810602, -0.76240719,  0.38433291],
       [ 1.6713659 ,  0.64414281,  0.73095606]])

In [31]:
np.random.randint(3,100)

78

In [34]:
x.argmax()

9

In [35]:
x[0]

10.0

In [36]:
x[-1]

200.0

In [37]:
x[:10]

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [38]:
x[-5:4]

array([], dtype=float64)

In [39]:
x[-5:1]

array([], dtype=float64)

In [40]:
x[-5:-1]

array([115.55555556, 136.66666667, 157.77777778, 178.88888889])

In [41]:
y=x[5:10]=10

In [42]:
y

10

In [43]:
x

array([10.        , 31.11111111, 52.22222222, 73.33333333, 94.44444444,
       10.        , 10.        , 10.        , 10.        , 10.        ])

In [44]:
z=x.copy()

In [45]:
z

array([10.        , 31.11111111, 52.22222222, 73.33333333, 94.44444444,
       10.        , 10.        , 10.        , 10.        , 10.        ])

In [46]:
z[5:10]=80
z

array([10.        , 31.11111111, 52.22222222, 73.33333333, 94.44444444,
       80.        , 80.        , 80.        , 80.        , 80.        ])

In [47]:
x[2][3]

IndexError: invalid index to scalar variable.

In [48]:
q=np.arange(25).reshape(5,5)

In [49]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
q[2][3]

13

In [51]:
q[0][0]

0

In [52]:
np.cos(x)

array([-0.83907153,  0.95390236, -0.37643335, -0.47423423,  0.98072372,
       -0.83907153, -0.83907153, -0.83907153, -0.83907153, -0.83907153])

In [53]:
x.sum()

311.1111111111111

In [57]:
10^5

15

In [58]:
10^*5

SyntaxError: invalid syntax (<ipython-input-58-161156ebc70a>, line 1)

In [59]:
10**5

100000

In [61]:
def is_leap(year):
    if 1900<=year<=(10**5):

        if (year%4==0) or (year%100==0 and year%400==0):
            return True
        else:
            return False
    else:
        return False

year = int(input())
print(is_leap(year))

1800
False


In [62]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
lst = [] 
n = int(input("Enter number of elements : ")) 
for i in range(0, n): 
    ele = int(input()) 
    lst.append(ele) 
print(lst) 


In [1]:
pip3 install sortednp

SyntaxError: invalid syntax (<ipython-input-1-429d57e21a4d>, line 1)

In [4]:
import numpy as np
a=[1,2,3]
b=np.repeat(a,3)
c=np.tile(a,3)
r=np.concatenate((b,c))
e=np.merge(b,c)
e
r

AttributeError: module 'numpy' has no attribute 'merge'